# Generated by Django 5.2.7 on 2025-11-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('UPLOAD_COMPLETE', 'Upload Complete'), ('PROCESSING', 'Processing'), ('PROCESSING_HLS', 'Processing HLS'), ('READY', 'Ready'), ('ERROR', 'Error'), ('DELETING', 'Deleting')], default='UPLOADING', editable=False, max_length=32),
        ),
    ]
