# Generated by Django 5.2.7 on 2025-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storedfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['user', 'deleted_at', '-uploaded_at'], name='storedfile_user_deleted_idx'),
        ),
    ]
