version: "3.8"

services:
  web:
    build: .
    container_name: storage_web
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./secrets/gcs-key.json:/var/secrets/gcs-key.json:ro
    command: ./docker/entrypoint.sh
    depends_on:
      - redis

  celery:
    build: .
    container_name: storage_celery
    env_file: .env
    command: celery -A storage worker -l info
    volumes:
      - .:/app
      - ./secrets/gcs-key.json:/var/secrets/gcs-key.json:ro
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: storage_redis
